-- V12: Optimistic Locking için tüm tablolara version alanı eklenmesi

ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE department_budget ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE card ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE cheque ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE contact ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE employee ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE employee_task ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE expense ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE installment_entry ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE note ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
