CREATE TABLE card (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    bank VARCHAR(100) NOT NULL,
    card_limit NUMERIC(15,2) NOT NULL DEFAULT 0,
    category VARCHAR(50),
    color VARCHAR(7) DEFAULT '#1976D2',
    closing_day INT NOT NULL DEFAULT 1,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
