ALTER TABLE employee ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES department(id) ON DELETE SET NULL;
ALTER TABLE department ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE department_budget ADD COLUMN IF NOT EXISTS category VARCHAR(100);
