name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u rasimtuzluoglu --password-stdin
          docker build -t ghcr.io/rasimtuzluoglu/raspel-fin:latest .
          docker push ghcr.io/rasimtuzluoglu/raspel-fin:latest
